package investigationTest;

import java.io.Serializable;

/**
 * @author matias
 * 
 * Equals & HashCode generated by Eclipse
 *
 */
public class Something implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 2291995680262317065L;
	final public String key;
	final public int value;

	public Something(String key, int value) {
		this.key = key;
		this.value = value;
	}

	@Override
	public String toString() {
		return "concat [key=" + key + ", value=" + value + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((key == null) ? 0 : key.hashCode());
		result = prime * result + value;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Something other = (Something) obj;
		if (key == null) {
			if (other.key != null)
				return false;
		} else if (!key.equals(other.key))
			return false;
		if (value != other.value)
			return false;
		return true;
	}

}
